// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
)

// Defines values for MesgType.
const (
	Invoke MesgType = "invoke"
	Resume MesgType = "resume"
)

// Defines values for PromiseState.
const (
	PromiseStatePENDING          PromiseState = "PENDING"
	PromiseStateREJECTED         PromiseState = "REJECTED"
	PromiseStateREJECTEDCANCELED PromiseState = "REJECTED_CANCELED"
	PromiseStateREJECTEDTIMEDOUT PromiseState = "REJECTED_TIMEDOUT"
	PromiseStateRESOLVED         PromiseState = "RESOLVED"
)

// Defines values for SearchPromisesParamsState.
const (
	Pending  SearchPromisesParamsState = "pending"
	Rejected SearchPromisesParamsState = "rejected"
	Resolved SearchPromisesParamsState = "resolved"
)

// Defines values for CompletePromiseJSONBodyState.
const (
	CompletePromiseJSONBodyStateREJECTED         CompletePromiseJSONBodyState = "REJECTED"
	CompletePromiseJSONBodyStateREJECTEDCANCELED CompletePromiseJSONBodyState = "REJECTED_CANCELED"
	CompletePromiseJSONBodyStateRESOLVED         CompletePromiseJSONBodyState = "RESOLVED"
)

// Callback defines model for Callback.
type Callback struct {
	CreatedOn *int64 `json:"createdOn,omitempty"`
	Id        string `json:"id"`
	PromiseId string `json:"promiseId"`
	Timeout   int64  `json:"timeout"`
}

// Mesg defines model for Mesg.
type Mesg struct {
	Promises struct {
		Leaf *struct {
			Data Promise `json:"data"`
			Href string  `json:"href"`
			Id   string  `json:"id"`
		} `json:"leaf,omitempty"`
		Root *struct {
			Data Promise `json:"data"`
			Href string  `json:"href"`
			Id   string  `json:"id"`
		} `json:"root,omitempty"`
	} `json:"promises"`
	Type MesgType `json:"type"`
}

// MesgType defines model for Mesg.Type.
type MesgType string

// Promise defines model for Promise.
type Promise struct {
	CompletedOn *int64            `json:"completedOn,omitempty"`
	CreatedOn   *int64            `json:"createdOn,omitempty"`
	Id          string            `json:"id"`
	Param       Value             `json:"param"`
	State       PromiseState      `json:"state"`
	Tags        map[string]string `json:"tags"`
	Timeout     int64             `json:"timeout"`
	Value       Value             `json:"value"`
}

// PromiseState defines model for Promise.State.
type PromiseState string

// Recv defines model for Recv.
type Recv struct {
	union json.RawMessage
}

// Recv0 defines model for .
type Recv0 struct {
	Data map[string]interface{} `json:"data"`
	Type string                 `json:"type"`
}

// Recv1 defines model for .
type Recv1 = string

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedOn      *int64            `json:"createdOn,omitempty"`
	Cron           string            `json:"cron"`
	Description    string            `json:"description"`
	Id             string            `json:"id"`
	LastRunTime    *int64            `json:"lastRunTime,omitempty"`
	NextRunTime    *int64            `json:"nextRunTime,omitempty"`
	PromiseId      string            `json:"promiseId"`
	PromiseParam   Value             `json:"promiseParam"`
	PromiseTags    map[string]string `json:"promiseTags"`
	PromiseTimeout int64             `json:"promiseTimeout"`
	Tags           map[string]string `json:"tags"`
}

// Task defines model for Task.
type Task struct {
	CompletedOn *int64  `json:"completedOn,omitempty"`
	Counter     int     `json:"counter"`
	CreatedOn   *int64  `json:"createdOn,omitempty"`
	Id          string  `json:"id"`
	ProcessId   *string `json:"processId,omitempty"`
	Timeout     int64   `json:"timeout"`
}

// Value defines model for Value.
type Value struct {
	Data    *string            `json:"data,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
}

// SearchPromisesParams defines parameters for SearchPromises.
type SearchPromisesParams struct {
	// Id Search promises for matching ids, can include wildcards.
	//
	// For example:
	// - "foo/*" matches all ids starting with "foo/"
	// - "*/bar" matches all ids ending with "bar/"
	// - "foo/*/bar" matches all ids starting with "foo/" and ending with "/bar"
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// State Search promises for matching states
	State *SearchPromisesParamsState `form:"state,omitempty" json:"state,omitempty"`
	Tags  *map[string]string         `json:"tags,omitempty"`

	// Limit Number of results per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// SearchPromisesParamsState defines parameters for SearchPromises.
type SearchPromisesParamsState string

// CreatePromiseJSONBody defines parameters for CreatePromise.
type CreatePromiseJSONBody struct {
	Id      string             `json:"id"`
	Param   *Value             `json:"param,omitempty"`
	Tags    *map[string]string `json:"tags,omitempty"`
	Timeout int64              `json:"timeout"`
}

// CreatePromiseParams defines parameters for CreatePromise.
type CreatePromiseParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CreatePromiseCallbackJSONBody defines parameters for CreatePromiseCallback.
type CreatePromiseCallbackJSONBody struct {
	Recv          Recv   `json:"recv"`
	RootPromiseId string `json:"rootPromiseId"`
	Timeout       int64  `json:"timeout"`
}

// CreatePromiseCallbackParams defines parameters for CreatePromiseCallback.
type CreatePromiseCallbackParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CreatePromiseSubscriptionJSONBody defines parameters for CreatePromiseSubscription.
type CreatePromiseSubscriptionJSONBody struct {
	Id      string `json:"id"`
	Recv    Recv   `json:"recv"`
	Timeout int64  `json:"timeout"`
}

// CreatePromiseSubscriptionParams defines parameters for CreatePromiseSubscription.
type CreatePromiseSubscriptionParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CreatePromiseAndTaskJSONBody defines parameters for CreatePromiseAndTask.
type CreatePromiseAndTaskJSONBody struct {
	Promise struct {
		Id      string             `json:"id"`
		Param   *Value             `json:"param,omitempty"`
		Tags    *map[string]string `json:"tags,omitempty"`
		Timeout int64              `json:"timeout"`
	} `json:"promise"`
	Task struct {
		ProcessId string `json:"processId"`
		Ttl       int    `json:"ttl"`
	} `json:"task"`
}

// CreatePromiseAndTaskParams defines parameters for CreatePromiseAndTask.
type CreatePromiseAndTaskParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// ReadPromiseParams defines parameters for ReadPromise.
type ReadPromiseParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CompletePromiseJSONBody defines parameters for CompletePromise.
type CompletePromiseJSONBody struct {
	State CompletePromiseJSONBodyState `json:"state"`
	Value *Value                       `json:"value,omitempty"`
}

// CompletePromiseParams defines parameters for CompletePromise.
type CompletePromiseParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CompletePromiseJSONBodyState defines parameters for CompletePromise.
type CompletePromiseJSONBodyState string

// SearchSchedulesParams defines parameters for SearchSchedules.
type SearchSchedulesParams struct {
	// Id Search schedules for matching ids, can include wildcards.
	//
	// For example:
	// - "foo/*" matches all ids starting with "foo/"
	// - "*/bar" matches all ids ending with "bar/"
	// - "foo/*/bar" matches all ids starting with "foo/" and ending with "/bar"
	Id   *string            `form:"id,omitempty" json:"id,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`

	// Limit Number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CreateScheduleJSONBody defines parameters for CreateSchedule.
type CreateScheduleJSONBody struct {
	Cron           *string            `json:"cron,omitempty"`
	Description    *string            `json:"description,omitempty"`
	Id             *string            `json:"id,omitempty"`
	PromiseId      *string            `json:"promiseId,omitempty"`
	PromiseParam   *Value             `json:"promiseParam,omitempty"`
	PromiseTags    *map[string]string `json:"promiseTags,omitempty"`
	PromiseTimeout *int64             `json:"promiseTimeout,omitempty"`
	Tags           *map[string]string `json:"tags,omitempty"`
}

// CreateScheduleParams defines parameters for CreateSchedule.
type CreateScheduleParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// DeleteScheduleParams defines parameters for DeleteSchedule.
type DeleteScheduleParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// ReadScheduleParams defines parameters for ReadSchedule.
type ReadScheduleParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// ClaimTaskJSONBody defines parameters for ClaimTask.
type ClaimTaskJSONBody struct {
	// Counter The task counter
	Counter int `json:"counter"`

	// Id The task id
	Id string `json:"id"`

	// ProcessId Unique process id that identifies the claimer
	ProcessId string `json:"processId"`

	// Ttl Time to live in milliseconds
	Ttl int64 `json:"ttl"`
}

// ClaimTaskParams defines parameters for ClaimTask.
type ClaimTaskParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// ClaimTaskGetParams defines parameters for ClaimTaskGet.
type ClaimTaskGetParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CompleteTaskJSONBody defines parameters for CompleteTask.
type CompleteTaskJSONBody struct {
	// Counter The task counter
	Counter int `json:"counter"`

	// Id The task id
	Id string `json:"id"`
}

// CompleteTaskGetParams defines parameters for CompleteTaskGet.
type CompleteTaskGetParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// DropTaskJSONBody defines parameters for DropTask.
type DropTaskJSONBody struct {
	// Counter The task counter
	Counter int `json:"counter"`

	// Id The task id
	Id string `json:"id"`
}

// DropTaskGetParams defines parameters for DropTaskGet.
type DropTaskGetParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// HeartbeatTasksJSONBody defines parameters for HeartbeatTasks.
type HeartbeatTasksJSONBody struct {
	ProcessId string `json:"processId"`
}

// HeartbeatTasksParams defines parameters for HeartbeatTasks.
type HeartbeatTasksParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// HeartbeatTaskGetParams defines parameters for HeartbeatTaskGet.
type HeartbeatTaskGetParams struct {
	// RequestId Unique tracking id
	RequestId *string `json:"request-id,omitempty"`
}

// CreatePromiseJSONRequestBody defines body for CreatePromise for application/json ContentType.
type CreatePromiseJSONRequestBody CreatePromiseJSONBody

// CreatePromiseCallbackJSONRequestBody defines body for CreatePromiseCallback for application/json ContentType.
type CreatePromiseCallbackJSONRequestBody CreatePromiseCallbackJSONBody

// CreatePromiseSubscriptionJSONRequestBody defines body for CreatePromiseSubscription for application/json ContentType.
type CreatePromiseSubscriptionJSONRequestBody CreatePromiseSubscriptionJSONBody

// CreatePromiseAndTaskJSONRequestBody defines body for CreatePromiseAndTask for application/json ContentType.
type CreatePromiseAndTaskJSONRequestBody CreatePromiseAndTaskJSONBody

// CompletePromiseJSONRequestBody defines body for CompletePromise for application/json ContentType.
type CompletePromiseJSONRequestBody CompletePromiseJSONBody

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody CreateScheduleJSONBody

// ClaimTaskJSONRequestBody defines body for ClaimTask for application/json ContentType.
type ClaimTaskJSONRequestBody ClaimTaskJSONBody

// CompleteTaskJSONRequestBody defines body for CompleteTask for application/json ContentType.
type CompleteTaskJSONRequestBody CompleteTaskJSONBody

// DropTaskJSONRequestBody defines body for DropTask for application/json ContentType.
type DropTaskJSONRequestBody DropTaskJSONBody

// HeartbeatTasksJSONRequestBody defines body for HeartbeatTasks for application/json ContentType.
type HeartbeatTasksJSONRequestBody HeartbeatTasksJSONBody

// AsRecv0 returns the union data inside the Recv as a Recv0
func (t Recv) AsRecv0() (Recv0, error) { _ = "STUB: not implemented"; return *new(Recv0), nil }

// FromRecv0 overwrites any union data inside the Recv as the provided Recv0
func (t *Recv) FromRecv0(v Recv0) error { _ = "STUB: not implemented"; return nil }

// MergeRecv0 performs a merge with any union data inside the Recv, using the provided Recv0
func (t *Recv) MergeRecv0(v Recv0) error { _ = "STUB: not implemented"; return nil }

// AsRecv1 returns the union data inside the Recv as a Recv1
func (t Recv) AsRecv1() (Recv1, error) { _ = "STUB: not implemented"; return *new(Recv1), nil }

// FromRecv1 overwrites any union data inside the Recv as the provided Recv1
func (t *Recv) FromRecv1(v Recv1) error { _ = "STUB: not implemented"; return nil }

// MergeRecv1 performs a merge with any union data inside the Recv, using the provided Recv1
func (t *Recv) MergeRecv1(v Recv1) error { _ = "STUB: not implemented"; return nil }

func (t Recv) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (t *Recv) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	// create a client with sane default values
	return nil, nil
}

// mutate client and add all optional params

// ensure the server URL always has a trailing slash

// create httpClient, if not already present

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// The interface specification for the client above.
type ClientInterface interface {
	// SearchPromises request
	SearchPromises(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePromiseWithBody request with any body
	CreatePromiseWithBody(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePromise(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePromiseCallbackWithBody request with any body
	CreatePromiseCallbackWithBody(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePromiseCallback(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePromiseSubscriptionWithBody request with any body
	CreatePromiseSubscriptionWithBody(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePromiseSubscription(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePromiseAndTaskWithBody request with any body
	CreatePromiseAndTaskWithBody(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePromiseAndTask(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReadPromise request
	ReadPromise(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompletePromiseWithBody request with any body
	CompletePromiseWithBody(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompletePromise(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchSchedules request
	SearchSchedules(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateScheduleWithBody request with any body
	CreateScheduleWithBody(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSchedule(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSchedule request
	DeleteSchedule(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReadSchedule request
	ReadSchedule(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimTaskWithBody request with any body
	ClaimTaskWithBody(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ClaimTask(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimTaskGet request
	ClaimTaskGet(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteTaskWithBody request with any body
	CompleteTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteTask(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteTaskGet request
	CompleteTaskGet(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DropTaskWithBody request with any body
	DropTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DropTask(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DropTaskGet request
	DropTaskGet(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatTasksWithBody request with any body
	HeartbeatTasksWithBody(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HeartbeatTasks(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatTaskGet request
	HeartbeatTaskGet(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SearchPromises(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseWithBody(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromise(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseCallbackWithBody(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseCallback(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseSubscriptionWithBody(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseSubscription(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseAndTaskWithBody(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreatePromiseAndTask(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) ReadPromise(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CompletePromiseWithBody(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CompletePromise(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) SearchSchedules(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreateScheduleWithBody(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CreateSchedule(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DeleteSchedule(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) ReadSchedule(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) ClaimTaskWithBody(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) ClaimTask(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) ClaimTaskGet(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CompleteTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CompleteTask(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) CompleteTaskGet(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DropTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DropTask(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) DropTaskGet(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) HeartbeatTasksWithBody(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) HeartbeatTasks(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) HeartbeatTaskGet(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewSearchPromisesRequest generates requests for SearchPromises
func NewSearchPromisesRequest(server string, params *SearchPromisesParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseRequest calls the generic CreatePromise builder with application/json body
func NewCreatePromiseRequest(server string, params *CreatePromiseParams, body CreatePromiseJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseRequestWithBody generates requests for CreatePromise with any type of body
func NewCreatePromiseRequestWithBody(server string, params *CreatePromiseParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseCallbackRequest calls the generic CreatePromiseCallback builder with application/json body
func NewCreatePromiseCallbackRequest(server string, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseCallbackRequestWithBody generates requests for CreatePromiseCallback with any type of body
func NewCreatePromiseCallbackRequestWithBody(server string, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseSubscriptionRequest calls the generic CreatePromiseSubscription builder with application/json body
func NewCreatePromiseSubscriptionRequest(server string, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseSubscriptionRequestWithBody generates requests for CreatePromiseSubscription with any type of body
func NewCreatePromiseSubscriptionRequestWithBody(server string, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseAndTaskRequest calls the generic CreatePromiseAndTask builder with application/json body
func NewCreatePromiseAndTaskRequest(server string, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreatePromiseAndTaskRequestWithBody generates requests for CreatePromiseAndTask with any type of body
func NewCreatePromiseAndTaskRequestWithBody(server string, params *CreatePromiseAndTaskParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewReadPromiseRequest generates requests for ReadPromise
func NewReadPromiseRequest(server string, id string, params *ReadPromiseParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCompletePromiseRequest calls the generic CompletePromise builder with application/json body
func NewCompletePromiseRequest(server string, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCompletePromiseRequestWithBody generates requests for CompletePromise with any type of body
func NewCompletePromiseRequestWithBody(server string, id string, params *CompletePromiseParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewSearchSchedulesRequest generates requests for SearchSchedules
func NewSearchSchedulesRequest(server string, params *SearchSchedulesParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreateScheduleRequest calls the generic CreateSchedule builder with application/json body
func NewCreateScheduleRequest(server string, params *CreateScheduleParams, body CreateScheduleJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCreateScheduleRequestWithBody generates requests for CreateSchedule with any type of body
func NewCreateScheduleRequestWithBody(server string, params *CreateScheduleParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteScheduleRequest generates requests for DeleteSchedule
func NewDeleteScheduleRequest(server string, id string, params *DeleteScheduleParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewReadScheduleRequest generates requests for ReadSchedule
func NewReadScheduleRequest(server string, id string, params *ReadScheduleParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewClaimTaskRequest calls the generic ClaimTask builder with application/json body
func NewClaimTaskRequest(server string, params *ClaimTaskParams, body ClaimTaskJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewClaimTaskRequestWithBody generates requests for ClaimTask with any type of body
func NewClaimTaskRequestWithBody(server string, params *ClaimTaskParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewClaimTaskGetRequest generates requests for ClaimTaskGet
func NewClaimTaskGetRequest(server string, id string, counter int, params *ClaimTaskGetParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCompleteTaskRequest calls the generic CompleteTask builder with application/json body
func NewCompleteTaskRequest(server string, body CompleteTaskJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCompleteTaskRequestWithBody generates requests for CompleteTask with any type of body
func NewCompleteTaskRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewCompleteTaskGetRequest generates requests for CompleteTaskGet
func NewCompleteTaskGetRequest(server string, id string, counter int, params *CompleteTaskGetParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDropTaskRequest calls the generic DropTask builder with application/json body
func NewDropTaskRequest(server string, body DropTaskJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDropTaskRequestWithBody generates requests for DropTask with any type of body
func NewDropTaskRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDropTaskGetRequest generates requests for DropTaskGet
func NewDropTaskGetRequest(server string, id string, counter int, params *DropTaskGetParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewHeartbeatTasksRequest calls the generic HeartbeatTasks builder with application/json body
func NewHeartbeatTasksRequest(server string, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewHeartbeatTasksRequestWithBody generates requests for HeartbeatTasks with any type of body
func NewHeartbeatTasksRequestWithBody(server string, params *HeartbeatTasksParams, contentType string, body io.Reader) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewHeartbeatTaskGetRequest generates requests for HeartbeatTaskGet
func NewHeartbeatTaskGetRequest(server string, id string, counter int, params *HeartbeatTaskGetParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	_ = "STUB: not implemented"
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption { _ = "STUB: not implemented"; return *new(ClientOption) }

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SearchPromisesWithResponse request
	SearchPromisesWithResponse(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*SearchPromisesResponse, error)

	// CreatePromiseWithBodyWithResponse request with any body
	CreatePromiseWithBodyWithResponse(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error)

	CreatePromiseWithResponse(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error)

	// CreatePromiseCallbackWithBodyWithResponse request with any body
	CreatePromiseCallbackWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error)

	CreatePromiseCallbackWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error)

	// CreatePromiseSubscriptionWithBodyWithResponse request with any body
	CreatePromiseSubscriptionWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error)

	CreatePromiseSubscriptionWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error)

	// CreatePromiseAndTaskWithBodyWithResponse request with any body
	CreatePromiseAndTaskWithBodyWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error)

	CreatePromiseAndTaskWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error)

	// ReadPromiseWithResponse request
	ReadPromiseWithResponse(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*ReadPromiseResponse, error)

	// CompletePromiseWithBodyWithResponse request with any body
	CompletePromiseWithBodyWithResponse(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error)

	CompletePromiseWithResponse(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error)

	// SearchSchedulesWithResponse request
	SearchSchedulesWithResponse(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*SearchSchedulesResponse, error)

	// CreateScheduleWithBodyWithResponse request with any body
	CreateScheduleWithBodyWithResponse(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error)

	CreateScheduleWithResponse(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error)

	// DeleteScheduleWithResponse request
	DeleteScheduleWithResponse(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*DeleteScheduleResponse, error)

	// ReadScheduleWithResponse request
	ReadScheduleWithResponse(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*ReadScheduleResponse, error)

	// ClaimTaskWithBodyWithResponse request with any body
	ClaimTaskWithBodyWithResponse(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error)

	ClaimTaskWithResponse(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error)

	// ClaimTaskGetWithResponse request
	ClaimTaskGetWithResponse(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*ClaimTaskGetResponse, error)

	// CompleteTaskWithBodyWithResponse request with any body
	CompleteTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error)

	CompleteTaskWithResponse(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error)

	// CompleteTaskGetWithResponse request
	CompleteTaskGetWithResponse(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*CompleteTaskGetResponse, error)

	// DropTaskWithBodyWithResponse request with any body
	DropTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DropTaskResponse, error)

	DropTaskWithResponse(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*DropTaskResponse, error)

	// DropTaskGetWithResponse request
	DropTaskGetWithResponse(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*DropTaskGetResponse, error)

	// HeartbeatTasksWithBodyWithResponse request with any body
	HeartbeatTasksWithBodyWithResponse(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error)

	HeartbeatTasksWithResponse(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error)

	// HeartbeatTaskGetWithResponse request
	HeartbeatTaskGetWithResponse(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*HeartbeatTaskGetResponse, error)
}

type SearchPromisesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cursor   *string    `json:"cursor,omitempty"`
		Promises *[]Promise `json:"promises,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r SearchPromisesResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r SearchPromisesResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CreatePromiseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Promise
	JSON201      *Promise
}

// Status returns HTTPResponse.Status
func (r CreatePromiseResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePromiseResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CreatePromiseCallbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Promise *Promise `json:"promise,omitempty"`
	}
	JSON201 *struct {
		Callback *Callback `json:"callback,omitempty"`
		Promise  *Promise  `json:"promise,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreatePromiseCallbackResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePromiseCallbackResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CreatePromiseSubscriptionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Promise *Promise `json:"promise,omitempty"`
	}
	JSON201 *struct {
		Callback *Callback `json:"callback,omitempty"`
		Promise  *Promise  `json:"promise,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreatePromiseSubscriptionResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePromiseSubscriptionResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CreatePromiseAndTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Promise *Promise `json:"promise,omitempty"`
	}
	JSON201 *struct {
		Promise *Promise `json:"promise,omitempty"`
		Task    *Task    `json:"task,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreatePromiseAndTaskResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePromiseAndTaskResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type ReadPromiseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Promise
}

// Status returns HTTPResponse.Status
func (r ReadPromiseResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r ReadPromiseResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CompletePromiseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Promise
}

// Status returns HTTPResponse.Status
func (r CompletePromiseResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CompletePromiseResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type SearchSchedulesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cursor    *string     `json:"cursor,omitempty"`
		Schedules *[]Schedule `json:"schedules,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r SearchSchedulesResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r SearchSchedulesResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CreateScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cron           string             `json:"cron"`
		Description    *string            `json:"description,omitempty"`
		Id             string             `json:"id"`
		PromiseId      string             `json:"promiseId"`
		PromiseParam   *Value             `json:"promiseParam,omitempty"`
		PromiseTags    *map[string]string `json:"promiseTags,omitempty"`
		PromiseTimeout int64              `json:"promiseTimeout"`
		Tags           *map[string]string `json:"tags,omitempty"`
	}
	JSON201 *Schedule
}

// Status returns HTTPResponse.Status
func (r CreateScheduleResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CreateScheduleResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DeleteScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteScheduleResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteScheduleResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type ReadScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Schedule
}

// Status returns HTTPResponse.Status
func (r ReadScheduleResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r ReadScheduleResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type ClaimTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Mesg
}

// Status returns HTTPResponse.Status
func (r ClaimTaskResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r ClaimTaskResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type ClaimTaskGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Mesg
}

// Status returns HTTPResponse.Status
func (r ClaimTaskGetResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r ClaimTaskGetResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CompleteTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Task
}

// Status returns HTTPResponse.Status
func (r CompleteTaskResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteTaskResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type CompleteTaskGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Task
}

// Status returns HTTPResponse.Status
func (r CompleteTaskGetResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteTaskGetResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DropTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DropTaskResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r DropTaskResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type DropTaskGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DropTaskGetResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r DropTaskGetResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type HeartbeatTasksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		TasksAffected *int64 `json:"tasksAffected,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r HeartbeatTasksResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r HeartbeatTasksResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type HeartbeatTaskGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		TasksAffected *int64 `json:"tasksAffected,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r HeartbeatTaskGetResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r HeartbeatTaskGetResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

// SearchPromisesWithResponse request returning *SearchPromisesResponse
func (c *ClientWithResponses) SearchPromisesWithResponse(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*SearchPromisesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseWithBodyWithResponse request with arbitrary body returning *CreatePromiseResponse
func (c *ClientWithResponses) CreatePromiseWithBodyWithResponse(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CreatePromiseWithResponse(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseCallbackWithBodyWithResponse request with arbitrary body returning *CreatePromiseCallbackResponse
func (c *ClientWithResponses) CreatePromiseCallbackWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CreatePromiseCallbackWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseSubscriptionWithBodyWithResponse request with arbitrary body returning *CreatePromiseSubscriptionResponse
func (c *ClientWithResponses) CreatePromiseSubscriptionWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CreatePromiseSubscriptionWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseAndTaskWithBodyWithResponse request with arbitrary body returning *CreatePromiseAndTaskResponse
func (c *ClientWithResponses) CreatePromiseAndTaskWithBodyWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CreatePromiseAndTaskWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadPromiseWithResponse request returning *ReadPromiseResponse
func (c *ClientWithResponses) ReadPromiseWithResponse(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*ReadPromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompletePromiseWithBodyWithResponse request with arbitrary body returning *CompletePromiseResponse
func (c *ClientWithResponses) CompletePromiseWithBodyWithResponse(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CompletePromiseWithResponse(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchSchedulesWithResponse request returning *SearchSchedulesResponse
func (c *ClientWithResponses) SearchSchedulesWithResponse(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*SearchSchedulesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateScheduleWithBodyWithResponse request with arbitrary body returning *CreateScheduleResponse
func (c *ClientWithResponses) CreateScheduleWithBodyWithResponse(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CreateScheduleWithResponse(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScheduleWithResponse request returning *DeleteScheduleResponse
func (c *ClientWithResponses) DeleteScheduleWithResponse(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*DeleteScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadScheduleWithResponse request returning *ReadScheduleResponse
func (c *ClientWithResponses) ReadScheduleWithResponse(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*ReadScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskWithBodyWithResponse request with arbitrary body returning *ClaimTaskResponse
func (c *ClientWithResponses) ClaimTaskWithBodyWithResponse(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) ClaimTaskWithResponse(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskGetWithResponse request returning *ClaimTaskGetResponse
func (c *ClientWithResponses) ClaimTaskGetWithResponse(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*ClaimTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskWithBodyWithResponse request with arbitrary body returning *CompleteTaskResponse
func (c *ClientWithResponses) CompleteTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) CompleteTaskWithResponse(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskGetWithResponse request returning *CompleteTaskGetResponse
func (c *ClientWithResponses) CompleteTaskGetWithResponse(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*CompleteTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskWithBodyWithResponse request with arbitrary body returning *DropTaskResponse
func (c *ClientWithResponses) DropTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DropTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) DropTaskWithResponse(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*DropTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskGetWithResponse request returning *DropTaskGetResponse
func (c *ClientWithResponses) DropTaskGetWithResponse(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*DropTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTasksWithBodyWithResponse request with arbitrary body returning *HeartbeatTasksResponse
func (c *ClientWithResponses) HeartbeatTasksWithBodyWithResponse(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *ClientWithResponses) HeartbeatTasksWithResponse(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTaskGetWithResponse request returning *HeartbeatTaskGetResponse
func (c *ClientWithResponses) HeartbeatTaskGetWithResponse(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*HeartbeatTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseSearchPromisesResponse parses an HTTP response from a SearchPromisesWithResponse call
func ParseSearchPromisesResponse(rsp *http.Response) (*SearchPromisesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCreatePromiseResponse parses an HTTP response from a CreatePromiseWithResponse call
func ParseCreatePromiseResponse(rsp *http.Response) (*CreatePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCreatePromiseCallbackResponse parses an HTTP response from a CreatePromiseCallbackWithResponse call
func ParseCreatePromiseCallbackResponse(rsp *http.Response) (*CreatePromiseCallbackResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCreatePromiseSubscriptionResponse parses an HTTP response from a CreatePromiseSubscriptionWithResponse call
func ParseCreatePromiseSubscriptionResponse(rsp *http.Response) (*CreatePromiseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCreatePromiseAndTaskResponse parses an HTTP response from a CreatePromiseAndTaskWithResponse call
func ParseCreatePromiseAndTaskResponse(rsp *http.Response) (*CreatePromiseAndTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseReadPromiseResponse parses an HTTP response from a ReadPromiseWithResponse call
func ParseReadPromiseResponse(rsp *http.Response) (*ReadPromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCompletePromiseResponse parses an HTTP response from a CompletePromiseWithResponse call
func ParseCompletePromiseResponse(rsp *http.Response) (*CompletePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseSearchSchedulesResponse parses an HTTP response from a SearchSchedulesWithResponse call
func ParseSearchSchedulesResponse(rsp *http.Response) (*SearchSchedulesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCreateScheduleResponse parses an HTTP response from a CreateScheduleWithResponse call
func ParseCreateScheduleResponse(rsp *http.Response) (*CreateScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseDeleteScheduleResponse parses an HTTP response from a DeleteScheduleWithResponse call
func ParseDeleteScheduleResponse(rsp *http.Response) (*DeleteScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseReadScheduleResponse parses an HTTP response from a ReadScheduleWithResponse call
func ParseReadScheduleResponse(rsp *http.Response) (*ReadScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseClaimTaskResponse parses an HTTP response from a ClaimTaskWithResponse call
func ParseClaimTaskResponse(rsp *http.Response) (*ClaimTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseClaimTaskGetResponse parses an HTTP response from a ClaimTaskGetWithResponse call
func ParseClaimTaskGetResponse(rsp *http.Response) (*ClaimTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCompleteTaskResponse parses an HTTP response from a CompleteTaskWithResponse call
func ParseCompleteTaskResponse(rsp *http.Response) (*CompleteTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseCompleteTaskGetResponse parses an HTTP response from a CompleteTaskGetWithResponse call
func ParseCompleteTaskGetResponse(rsp *http.Response) (*CompleteTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseDropTaskResponse parses an HTTP response from a DropTaskWithResponse call
func ParseDropTaskResponse(rsp *http.Response) (*DropTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseDropTaskGetResponse parses an HTTP response from a DropTaskGetWithResponse call
func ParseDropTaskGetResponse(rsp *http.Response) (*DropTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseHeartbeatTasksResponse parses an HTTP response from a HeartbeatTasksWithResponse call
func ParseHeartbeatTasksResponse(rsp *http.Response) (*HeartbeatTasksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseHeartbeatTaskGetResponse parses an HTTP response from a HeartbeatTaskGetWithResponse call
func ParseHeartbeatTaskGetResponse(rsp *http.Response) (*HeartbeatTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
