// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/client/v1/v1.go
//
// Generated by this command:
//
//	mockgen -package v1 -source=pkg/client/v1/v1.go -destination=pkg/client/v1/v1_mock.go
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	io "io"
	http "net/http"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	_ = "STUB: not implemented"

	// Do mocks base method.
	return nil
}

func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// ClaimTask mocks base method.
	return nil
}

func (m *MockClientInterface) ClaimTask(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTask indicates an expected call of ClaimTask.
func (mr *MockClientInterfaceMockRecorder) ClaimTask(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ClaimTaskGet mocks base method.
func (m *MockClientInterface) ClaimTaskGet(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskGet indicates an expected call of ClaimTaskGet.
func (mr *MockClientInterfaceMockRecorder) ClaimTaskGet(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ClaimTaskWithBody mocks base method.
func (m *MockClientInterface) ClaimTaskWithBody(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskWithBody indicates an expected call of ClaimTaskWithBody.
func (mr *MockClientInterfaceMockRecorder) ClaimTaskWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompletePromise mocks base method.
func (m *MockClientInterface) CompletePromise(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompletePromise indicates an expected call of CompletePromise.
func (mr *MockClientInterfaceMockRecorder) CompletePromise(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompletePromiseWithBody mocks base method.
func (m *MockClientInterface) CompletePromiseWithBody(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompletePromiseWithBody indicates an expected call of CompletePromiseWithBody.
func (mr *MockClientInterfaceMockRecorder) CompletePromiseWithBody(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTask mocks base method.
func (m *MockClientInterface) CompleteTask(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockClientInterfaceMockRecorder) CompleteTask(ctx, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTaskGet mocks base method.
func (m *MockClientInterface) CompleteTaskGet(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskGet indicates an expected call of CompleteTaskGet.
func (mr *MockClientInterfaceMockRecorder) CompleteTaskGet(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTaskWithBody mocks base method.
func (m *MockClientInterface) CompleteTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskWithBody indicates an expected call of CompleteTaskWithBody.
func (mr *MockClientInterfaceMockRecorder) CompleteTaskWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromise mocks base method.
func (m *MockClientInterface) CreatePromise(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromise indicates an expected call of CreatePromise.
func (mr *MockClientInterfaceMockRecorder) CreatePromise(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseAndTask mocks base method.
func (m *MockClientInterface) CreatePromiseAndTask(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseAndTask indicates an expected call of CreatePromiseAndTask.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseAndTask(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseAndTaskWithBody mocks base method.
func (m *MockClientInterface) CreatePromiseAndTaskWithBody(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseAndTaskWithBody indicates an expected call of CreatePromiseAndTaskWithBody.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseAndTaskWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseCallback mocks base method.
func (m *MockClientInterface) CreatePromiseCallback(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseCallback indicates an expected call of CreatePromiseCallback.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseCallback(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseCallbackWithBody mocks base method.
func (m *MockClientInterface) CreatePromiseCallbackWithBody(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseCallbackWithBody indicates an expected call of CreatePromiseCallbackWithBody.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseCallbackWithBody(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseSubscription mocks base method.
func (m *MockClientInterface) CreatePromiseSubscription(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseSubscription indicates an expected call of CreatePromiseSubscription.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseSubscription(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseSubscriptionWithBody mocks base method.
func (m *MockClientInterface) CreatePromiseSubscriptionWithBody(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseSubscriptionWithBody indicates an expected call of CreatePromiseSubscriptionWithBody.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseSubscriptionWithBody(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseWithBody mocks base method.
func (m *MockClientInterface) CreatePromiseWithBody(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseWithBody indicates an expected call of CreatePromiseWithBody.
func (mr *MockClientInterfaceMockRecorder) CreatePromiseWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSchedule mocks base method.
func (m *MockClientInterface) CreateSchedule(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockClientInterfaceMockRecorder) CreateSchedule(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateScheduleWithBody mocks base method.
func (m *MockClientInterface) CreateScheduleWithBody(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateScheduleWithBody indicates an expected call of CreateScheduleWithBody.
func (mr *MockClientInterfaceMockRecorder) CreateScheduleWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSchedule mocks base method.
func (m *MockClientInterface) DeleteSchedule(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockClientInterfaceMockRecorder) DeleteSchedule(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTask mocks base method.
func (m *MockClientInterface) DropTask(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTask indicates an expected call of DropTask.
func (mr *MockClientInterfaceMockRecorder) DropTask(ctx, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTaskGet mocks base method.
func (m *MockClientInterface) DropTaskGet(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskGet indicates an expected call of DropTaskGet.
func (mr *MockClientInterfaceMockRecorder) DropTaskGet(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTaskWithBody mocks base method.
func (m *MockClientInterface) DropTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskWithBody indicates an expected call of DropTaskWithBody.
func (mr *MockClientInterfaceMockRecorder) DropTaskWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTaskGet mocks base method.
func (m *MockClientInterface) HeartbeatTaskGet(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTaskGet indicates an expected call of HeartbeatTaskGet.
func (mr *MockClientInterfaceMockRecorder) HeartbeatTaskGet(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTasks mocks base method.
func (m *MockClientInterface) HeartbeatTasks(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTasks indicates an expected call of HeartbeatTasks.
func (mr *MockClientInterfaceMockRecorder) HeartbeatTasks(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTasksWithBody mocks base method.
func (m *MockClientInterface) HeartbeatTasksWithBody(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTasksWithBody indicates an expected call of HeartbeatTasksWithBody.
func (mr *MockClientInterfaceMockRecorder) HeartbeatTasksWithBody(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadPromise mocks base method.
func (m *MockClientInterface) ReadPromise(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadPromise indicates an expected call of ReadPromise.
func (mr *MockClientInterfaceMockRecorder) ReadPromise(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadSchedule mocks base method.
func (m *MockClientInterface) ReadSchedule(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadSchedule indicates an expected call of ReadSchedule.
func (mr *MockClientInterfaceMockRecorder) ReadSchedule(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchPromises mocks base method.
func (m *MockClientInterface) SearchPromises(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchPromises indicates an expected call of SearchPromises.
func (mr *MockClientInterfaceMockRecorder) SearchPromises(ctx, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchSchedules mocks base method.
func (m *MockClientInterface) SearchSchedules(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchSchedules indicates an expected call of SearchSchedules.
func (mr *MockClientInterfaceMockRecorder) SearchSchedules(ctx, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	_ = "STUB: not implemented"

	// ClaimTaskGetWithResponse mocks base method.
	return nil
}

func (m *MockClientWithResponsesInterface) ClaimTaskGetWithResponse(ctx context.Context, id string, counter int, params *ClaimTaskGetParams, reqEditors ...RequestEditorFn) (*ClaimTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskGetWithResponse indicates an expected call of ClaimTaskGetWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ClaimTaskGetWithResponse(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ClaimTaskWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ClaimTaskWithBodyWithResponse(ctx context.Context, params *ClaimTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskWithBodyWithResponse indicates an expected call of ClaimTaskWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ClaimTaskWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ClaimTaskWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ClaimTaskWithResponse(ctx context.Context, params *ClaimTaskParams, body ClaimTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClaimTaskWithResponse indicates an expected call of ClaimTaskWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ClaimTaskWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompletePromiseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CompletePromiseWithBodyWithResponse(ctx context.Context, id string, params *CompletePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompletePromiseWithBodyWithResponse indicates an expected call of CompletePromiseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CompletePromiseWithBodyWithResponse(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompletePromiseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CompletePromiseWithResponse(ctx context.Context, id string, params *CompletePromiseParams, body CompletePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CompletePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompletePromiseWithResponse indicates an expected call of CompletePromiseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CompletePromiseWithResponse(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTaskGetWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CompleteTaskGetWithResponse(ctx context.Context, id string, counter int, params *CompleteTaskGetParams, reqEditors ...RequestEditorFn) (*CompleteTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskGetWithResponse indicates an expected call of CompleteTaskGetWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CompleteTaskGetWithResponse(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTaskWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CompleteTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskWithBodyWithResponse indicates an expected call of CompleteTaskWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CompleteTaskWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteTaskWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CompleteTaskWithResponse(ctx context.Context, body CompleteTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CompleteTaskWithResponse indicates an expected call of CompleteTaskWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CompleteTaskWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseAndTaskWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseAndTaskWithBodyWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseAndTaskWithBodyWithResponse indicates an expected call of CreatePromiseAndTaskWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseAndTaskWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseAndTaskWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseAndTaskWithResponse(ctx context.Context, params *CreatePromiseAndTaskParams, body CreatePromiseAndTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseAndTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseAndTaskWithResponse indicates an expected call of CreatePromiseAndTaskWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseAndTaskWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseCallbackWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseCallbackWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseCallbackWithBodyWithResponse indicates an expected call of CreatePromiseCallbackWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseCallbackWithBodyWithResponse(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseCallbackWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseCallbackWithResponse(ctx context.Context, id string, params *CreatePromiseCallbackParams, body CreatePromiseCallbackJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseCallbackResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseCallbackWithResponse indicates an expected call of CreatePromiseCallbackWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseCallbackWithResponse(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseSubscriptionWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseSubscriptionWithBodyWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseSubscriptionWithBodyWithResponse indicates an expected call of CreatePromiseSubscriptionWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseSubscriptionWithBodyWithResponse(ctx, id, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseSubscriptionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseSubscriptionWithResponse(ctx context.Context, id string, params *CreatePromiseSubscriptionParams, body CreatePromiseSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseSubscriptionWithResponse indicates an expected call of CreatePromiseSubscriptionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseSubscriptionWithResponse(ctx, id, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseWithBodyWithResponse(ctx context.Context, params *CreatePromiseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseWithBodyWithResponse indicates an expected call of CreatePromiseWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreatePromiseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreatePromiseWithResponse(ctx context.Context, params *CreatePromiseParams, body CreatePromiseJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreatePromiseWithResponse indicates an expected call of CreatePromiseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreatePromiseWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateScheduleWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateScheduleWithBodyWithResponse(ctx context.Context, params *CreateScheduleParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateScheduleWithBodyWithResponse indicates an expected call of CreateScheduleWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateScheduleWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateScheduleWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CreateScheduleWithResponse(ctx context.Context, params *CreateScheduleParams, body CreateScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateScheduleWithResponse indicates an expected call of CreateScheduleWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CreateScheduleWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteScheduleWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DeleteScheduleWithResponse(ctx context.Context, id string, params *DeleteScheduleParams, reqEditors ...RequestEditorFn) (*DeleteScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteScheduleWithResponse indicates an expected call of DeleteScheduleWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DeleteScheduleWithResponse(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTaskGetWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DropTaskGetWithResponse(ctx context.Context, id string, counter int, params *DropTaskGetParams, reqEditors ...RequestEditorFn) (*DropTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskGetWithResponse indicates an expected call of DropTaskGetWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DropTaskGetWithResponse(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTaskWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DropTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DropTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskWithBodyWithResponse indicates an expected call of DropTaskWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DropTaskWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DropTaskWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) DropTaskWithResponse(ctx context.Context, body DropTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*DropTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DropTaskWithResponse indicates an expected call of DropTaskWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) DropTaskWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTaskGetWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) HeartbeatTaskGetWithResponse(ctx context.Context, id string, counter int, params *HeartbeatTaskGetParams, reqEditors ...RequestEditorFn) (*HeartbeatTaskGetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTaskGetWithResponse indicates an expected call of HeartbeatTaskGetWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) HeartbeatTaskGetWithResponse(ctx, id, counter, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTasksWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) HeartbeatTasksWithBodyWithResponse(ctx context.Context, params *HeartbeatTasksParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTasksWithBodyWithResponse indicates an expected call of HeartbeatTasksWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) HeartbeatTasksWithBodyWithResponse(ctx, params, contentType, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HeartbeatTasksWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) HeartbeatTasksWithResponse(ctx context.Context, params *HeartbeatTasksParams, body HeartbeatTasksJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatTasksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HeartbeatTasksWithResponse indicates an expected call of HeartbeatTasksWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) HeartbeatTasksWithResponse(ctx, params, body any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadPromiseWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ReadPromiseWithResponse(ctx context.Context, id string, params *ReadPromiseParams, reqEditors ...RequestEditorFn) (*ReadPromiseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadPromiseWithResponse indicates an expected call of ReadPromiseWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ReadPromiseWithResponse(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadScheduleWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ReadScheduleWithResponse(ctx context.Context, id string, params *ReadScheduleParams, reqEditors ...RequestEditorFn) (*ReadScheduleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadScheduleWithResponse indicates an expected call of ReadScheduleWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ReadScheduleWithResponse(ctx, id, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchPromisesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SearchPromisesWithResponse(ctx context.Context, params *SearchPromisesParams, reqEditors ...RequestEditorFn) (*SearchPromisesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchPromisesWithResponse indicates an expected call of SearchPromisesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SearchPromisesWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SearchSchedulesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) SearchSchedulesWithResponse(ctx context.Context, params *SearchSchedulesParams, reqEditors ...RequestEditorFn) (*SearchSchedulesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchSchedulesWithResponse indicates an expected call of SearchSchedulesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) SearchSchedulesWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
